[PII-334] - GitFlow create init all and update commands
    * Added new init all function
    * Added new update command
    * Added helper functions for finding:
        * module root
        * is 'cwd' a git directory
        * branch management
    * Fixed branch deletion bug in hotfix finish
    * Added optional rebase flag to hotfix finish
    * Added checks to update commands to terminate script if merge fails.
    * Added update command to feature usage.

http://jira.internal.plus.net/browse/PII-335

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -54,6 +54,16 @@ has() {
 	echo " $@ " | grep -q " $(escape $item) "
 }
 
+##
+# Checks to see if there are un-committed changes
+#
+# @return bool
+#
+has_local_changes() {
+    git status | grep -q 'working directory clean\|nothing added to commit';
+    [ $? -eq 0 ] && return 1 || return 0;
+}
+
 # basic math
 min() { [ "$1" -le "$2" ] && echo "$1" || echo "$2"; }
 max() { [ "$1" -ge "$2" ] && echo "$1" || echo "$2"; }
@@ -325,6 +335,24 @@ require_branches_equal() {
 	fi
 }
 
+module_root() {
+    wd=$(pwd);
+    while [ ! -d ".git" ]  && [ "$(pwd)" != "/" ] ; do
+        cd ..;
+    done
+
+    if [ "$(pwd)" = "/" ] ; then
+        cd $wd;
+        warn "Cannot find git root directory for $(pwd). Are you sure it's a git repository?";
+        return 1;
+    fi
+    return 0;
+}
+
+is_git_dir() {
+    test -d $1/.git;
+}
+
 cmd_rename() {
     DEFINE_boolean force false 'Force branch renaming' r;
     DEFINE_boolean fetch false 'Fetch from origin before performing local operation' F;
@@ -365,7 +393,7 @@ cmd_rename() {
     fi
 
     # stash any current changes
-    if [ "$(git status | grep 'working directory clean\|nothing added to commit')" = "" ] ; then
+    if has_local_changes ; then
         git stash;
         FLAGS_stashed=$FLAGS_TRUE;
     fi
@@ -385,3 +413,32 @@ cmd_rename() {
         git stash pop;
     fi
 }
+
+is_feature() {
+   test "$PREFIX" = "$(git config gitflow.prefix.feature)";
+}
+
+is_hotfix() {
+    test "$PREFIX" = "$(git config gitflow.prefix.hotfix)";
+}
+
+is_release() {
+    test "$PREFIX" = "$(git config gitflow.prefix.release)";
+}
+
+is_support() {
+    test "$PREFIX" = "$(git config gitflow.prefix.support)";
+}
+
+current_branch() {
+    [ ! -z $BRANCH ] && echo $BRANCH || echo $(git_do rev-parse --abbrev-ref HEAD);
+}
+
+branch_valid() {
+    echo $(current_branch) | grep -q ^$PREFIX;
+}
+
+invalid_branch_for_command() {
+    die "Cannot run \`git flow $(echo $PREFIX | sed 's/.$//') update' command on a $(echo `current_branch` | cut -d- -f1) branch";
+}
+
