[PII-641] - Fixed issue with git-flow echoing gitflow dir contents
    * Random "echo '*'" left in place from previous commit
    * Added new interface for git-flow feature
    * More fixes to update command

http://jira.internal.plus.net/browse/PII-641

diff --git a/common/common-functions b/common/common-functions
--- a/common/common-functions
+++ b/common/common-functions
@@ -66,7 +66,7 @@ die() {
     fi
     message=$(__translate "$@");
     [ $nolog -eq 1 ] && log "[FATAL] $message";
-    pad_n _LINE_LEN '** '"$RED[$(__translate FATAL | tr '[:lower:]' '[:upper:]')]$RESET $message" ' ' '**' 1>&2;
+    pad_n _LINE_LEN "$RED[$(__translate FATAL | tr '[:lower:]' '[:upper:]')]$RESET $message" ' ' '' 1>&2;
     debug "Log file written to $_LOG_FILE";
     fill_n _SEP_LEN '**';
     exit 1;
@@ -87,7 +87,7 @@ info() {
     fi
     message=$(__translate "$@");
     [ $nolog -eq 1 ] && log "[INFO] $message";
-    pad_n _LINE_LEN '** '"$WHITE[$(__translate INFO | tr '[:lower:]' '[:upper:]')]$RESET $message" ' ' '**' 1>&2;
+    pad_n _LINE_LEN "$WHITE[$(__translate INFO | tr '[:lower:]' '[:upper:]')]$RESET $message" ' ' '' 1>&2;
 }
 
 ##
@@ -105,7 +105,7 @@ debug() {
     fi
     message=$(__translate "$@");
     [ $nolog -eq 1 ] && log "[DEBUG] $message";
-    pad_n _LINE_LEN '** '"$CYAN[$(__translate DEBUG | tr '[:lower:]' '[:upper:]')]$RESET $message" ' ' '**' 1>&2;
+    pad_n _LINE_LEN "$CYAN[$(__translate DEBUG | tr '[:lower:]' '[:upper:]')]$RESET $message" ' ' '' 1>&2;
 }
 
 ##
@@ -123,7 +123,7 @@ warn() {
     fi
     message=$(__translate "$@");
     [ $nolog -eq 1 ] && log "[WARNING] $message";
-    pad_n _LINE_LEN '** '"$(echo $YELLOW[$(__translate WARNING | tr '[:lower:]' '[:upper:]')]$RESET $message)" ' ' '**' 1>&2;
+    pad_n _LINE_LEN "$(echo $YELLOW[$(__translate WARNING | tr '[:lower:]' '[:upper:]')]$RESET $message)" ' ' '' 1>&2;
     __talk "$(__translate Warning) - '$message'";
 }
 
@@ -142,10 +142,77 @@ error() {
     fi
     message=$(__translate "$@");
     [ $nolog -eq 1 ] && log "[ERROR] $message";
-    pad_n _LINE_LEN '** '"$(echo $RED[$(__translate ERROR | tr '[:lower:]' '[:upper:]')] ${message}$RESET)" ' ' '**' 1>&2;
+    pad_n _LINE_LEN "$(echo $RED[$(__translate ERROR | tr '[:lower:]' '[:upper:]')] ${message}$RESET)" ' ' '' 1>&2;
     __talk $(__translate "Fail! An Error has occurred. Please check the output");
     __talk $(__translate "An Error has occurred. Error! Error!");
 }
+
+##
+# Read answer from user
+#
+# @param string Question
+#
+query()
+{
+    local nolog=1;
+    if [ "$1" = '--no-log' ] ; then
+        nolog=0;
+        shift;
+    fi
+
+    local message=$(__translate "$1");
+    shift;
+    [ $nolog -eq 1 ] && log "[INFO] $message";
+    if [ ${#1} -gt 0 ] ; then
+        echo "$WHITE[$(__translate INFO | tr '[:lower:]' '[:upper:]')]$RESET $message" ' ' '' 1>&2;
+        IFS='|' read -a opt <<< "$1";
+        for ((i = 0; $i < ${#opt[@]}; i++)); do
+            local option="$(echo ${opt[$i]} | cut -d: -f1)";
+            local help="$(echo ${opt[$i]} | cut -d: -f2)";
+            pad 12 "    - $option" ' ' 1>&2;
+            echo ": $help" 1>&2;
+        done;
+    else
+        echo -n "$WHITE[$(__translate INFO | tr '[:lower:]' '[:upper:]')]$RESET $message" ' ' '' 1>&2;
+        read answer;
+        echo "$answer";
+    fi
+}
+
+repeatQuestion()
+{
+    message="$1";
+    options="$2";
+
+    shortopts='';
+
+    IFS='|' read -a opt <<< "$options";
+    for ((i = 0; $i < ${#opt[@]}; i++)); do
+        local option="$(echo ${opt[$i]} | cut -d: -f1)";
+        if echo "$option" | grep -q '[0-9]\+\-[0-9]\+' ; then
+            for ((j=$(echo $option | cut -d- -f1); $j <=$(echo $option | cut -d- -f2); j++)); do
+                shortopts="$shortopts,$j";
+            done
+        else
+            shortopts="$shortopts,$option";
+        fi
+    done;
+    shortopts=$(echo $shortopts | sed 's/,//');
+
+    query "$message" "$options";
+    echo -n "$CYAN[ANSWER] > $RESET" 1>&2;
+    read answer;
+    if [ -n "$answer" ] ; then
+        if echo "$shortopts" | grep -q "$answer" ; then
+            echo "$answer"
+            return 0;
+        else
+            warn "Invalid option selected. No such option $answer";
+        fi
+    fi
+    repeatQuestion "$1" "$2"
+}
+
 
 ##
 # executes the given command
diff --git a/git-flow b/git-flow
--- a/git-flow
+++ b/git-flow
@@ -64,13 +64,12 @@ source "$GITFLOW_DIR/gitflow-common"
 # @return LAST_EXIT_STATUS
 #
 helper_lastBranch() {
-    [ ! $FORCE_MASTER ] && FORCE_MASTER=1;
     current=$1;
-    [ -z $current ] && current='master';
+    if [ $FORCE_MASTER -eq 0 ] || [ -z $current ] ; then
+        current='master'
+    fi
 
-    if [ $FORCE_MASTER -eq 0 ] ; then
-        git_do checkout master;
-    else
+    if [ "$(git rev-parse --abbrev-ref HEAD)" != "$current" ] ; then
         git_do checkout $current;
     fi
 }
@@ -81,16 +80,36 @@ helper_lastBranch() {
 # @return LAST_EXIT_STATUS
 #
 cmd_update() {
-    CWD=$(pwd);
-    cd $GITFLOW_DIR;
+    DEFINE_boolean force false "Force update of git flow" f;
+    FLAGS "$@" || exit $?;
+    eval set -- "${FLAGS_ARGV}";
 
+    CWD=$(pwd);
+    FORCE_MASTER=1; # force master branch unless gitflow.core.mode is set
+    cd $GITFLOW_DIR;
+    [ ! -n $UPDATE ] || UPDATE=1;
+
+    [ -n $ORIGIN ] && ORIGIN='origin';
+    current=$(git_do rev-parse --abbrev-ref HEAD);
+    lastUpdate=$(git_do config --get gitflow.core.lastupdate);
     mode=$(git_do config --get gitflow.core.mode);
     modeRetVal=$?;
-    if [ $modeRetVal -eq 2 ] ; then
-        error 'Invalid or broken .git/config - please fix and try again';
-        fill_n _SEP_LEN '*';
-        exit 1;
+
+    if [ $? -eq 1 ] ; then
+        lastUpdate=$(now);
+        git_do config --add gitflow.core.lastupdate $lastUpdate;
+        UPDATE=0;
     fi
+
+    info 'Checking for updates to GitFlow';
+
+    timestamp=$(timestamp 7);
+    if noflag force && [ $lastUpdate -ge $timestamp ] && [ $UPDATE -ne 0 ]; then
+        info "No update required (updated within last 7 days)";
+        cd $CWD;
+        return 0;
+    fi
+
     if [ $modeRetVal -eq 1 ] || [ "$mode" != 'develop' ]; then
         if [ "$mode" = 'skipupdate' ] ; then
             info "Skip update mode enabled - skipping update check";
@@ -100,48 +119,31 @@ cmd_update() {
             debug 'Invalid production mode - forcing master branch';
             FORCE_MASTER=0;
         fi
-    fi
-
-    fill_n _SEP_LEN '*';
-    info 'UPDATING GitFlow';
-
-    [ $1 ] && [ "$1" = '-f' ] && UPDATE=0;
-    if has_local_changes; then
-        error 'You have local changes to your GitFlow repository';
-        error 'Please stash or commit them first';
+    elif [ $modeRetVal -eq 2 ] ; then
+        error 'Invalid or broken .git/config - please fix and try again';
         fill_n _SEP_LEN '*';
         exit 1;
     fi
 
-    [ -n $ORIGIN ] && ORIGIN='origin';
-    current=$(git_do rev-parse --abbrev-ref HEAD);
+    if flag force || [ $lastUpdate -lt $timestamp ] || [ $UPDATE -eq 0 ]; then
+        if [ $modeRetVal -eq 2 ] ; then
+            error 'Invalid or broken .git/config - please fix and try again';
+            fill_n _SEP_LEN '*';
+            exit 1;
+        fi
 
-    FORCE_MASTER=1; # force master branch unless gitflow.core.mode is set
+        [ $1 ] && [ "$1" = '-f' ] && UPDATE=0;
+        if has_local_changes; then
+            error 'You have local changes to your GitFlow repository';
+            error 'Please stash or commit them first';
+            fill_n _SEP_LEN '*';
+            exit 1;
+        fi
 
-    # always start on master branch
-    if [ "$current" != 'master' ] ; then
-        git_do checkout master;
-    fi
-
-    [ ! -n $UPDATE ] || UPDATE=1;
-    lastUpdate=$(git_do config --get gitflow.core.lastupdate);
-    if [ $? -eq 1 ] ; then
-        lastUpdate=$(now);
-        git_do config --add gitflow.core.lastupdate $lastUpdate;
-        UPDATE=0;
-    fi
-
-    timestamp=$(timestamp 7);
-    if [ $lastUpdate -gt $timestamp ] ; then
-        info 'No update necessary - skipping';
-        helper_lastBranch "$current";
-        cd $CWD;
-        fill_n _SEP_LEN '*';
-        return 0;
-    fi
-
-    if [ $lastUpdate -ge $timestamp ] || [ $UPDATE -eq 0 ]; then
-        info 'Checking for updates to GitFlow';
+        # always start on master branch
+        if [ $FORCE_MASTER -eq 0 ] && [ "$current" != 'master' ] ; then
+            git_do checkout master;
+        fi
 
         git_compare_branches master $ORIGIN/master;
         retVal=$?;
@@ -152,7 +154,7 @@ cmd_update() {
             UPDATE=0;
         fi
     fi
-    if [ $UPDATE -eq 1 ] ; then
+    if [ $UPDATE -ne 1 ] ; then
         info 'There are updates available for GitFlow';
         echo -n '** Do you wish to install them? > ';
         read inst;
@@ -234,7 +236,7 @@ main() {
 	fi
 
     if [ "$SUBCOMMAND" = "update" ] ; then
-        cmd_update '-f';
+        cmd_update "$@";
         exit $?;
     else
         # auto-update if not run in 7 days
